### ISSUE TITLE
Misc Issues with 0.14.7

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#224]
Sheard creepers need a name: http://i.imgur.com/uSmQfYZ.png
Single Machines TE's are not named. Thus shows this when using Holoinventory http://imgur.com/dEg6iZp

Broken Craft/Minetweaker integration? http://pastebin.com/pgBiWTaB 
Script: http://pastebin.com/QwzBe9x4
Using CraftTweaker: 3.0.20

I'm not sure if you have control over this or not but Tinkers smelting of concentrated hellfire only uses one dust per ingot instead of the 8x dust in the cauldron. Just thought I'd bring that up.

**Comment by BeetoGuy** [comment]
CraftTweaker integration in newer versions requires MTLib to work. I'll add a localized name for sheared creepers, but it looks like HoloInventory doesn't grab the ".name" portion of the localization string for modded blocks. I'll have to see if just generically defining that as "Mechanical Machine" fixes it.
As for the concentrated hellfire, it seems to be something tied to the Ore Dictionary name, I'll probably revert it to "powderedHellfire" instead of "dustHellfire" for the time being.

**Comment by Claycorp** [comment]
I will tell dries about the HoloInventory stuff and see what he thinks.

Thanks for the quick reply! I'll keep an eye out for more issues.
