### ISSUE TITLE
Using filtered hopper to make hellfire - multiple peculiarities

### ISSUE THREAD

**Issue by Jleepevner** [BeetoGuy/BetterWithMods#275]
Better With Mods-1.0.8-1.11.2.jar
Client: forge-1.11.2-13.20.0.2250-universal.jar

Default configs except for hardcore redstone = false.

1.) Soul sand filter not immediately visible when inserted into filtered hopper.

Place a filtered hopper, put a piece of soul sand in the filter.
In BTW, the texture updates to show the soul sand filter visible from the top as soon as it is inserted in the filter slot. In BWM, the filter only becomes externally visible after one ground netherrack is dropped in.

2.) Inconsistent behavior when dropping single vs multiple ground netherrack.

Place a filtered hopper, put a piece of soul sand in the filter.
Drop 1 ground netherrack in. Open your inventory, drop 6 ground netherrack in at once. When it blows up, only two will be converted into hellfire dust, 4 will still be ground netherrack, and one will have disappeared.

When using the filtered hopper and soul sand, it seems that the first piece of ground netherrack dropped in (whether a single item dropped with Q, or multiple items dropped in a single stack via the inventory) go straight into the inventory of the filtered hopper, rather than being converted to hellfire.

**Comment by BeetoGuy** [comment]
Yeah, the first issue (and the last part) is related to the tile entity not updating properly, since certain things aren't marked until the next time the inventory changes, so the hopper doesn't know it's supposed to be looking for those recipes. Seems like the second issue is related to inconsistency in the recipe handler, since it's increasing the soul count by the EntityItem's stack size, rather than one at a time like how the ground netherrack gets converted.
