### ISSUE TITLE
[1.11.2] Upgrading from 1.1.6 to 1.1.7 seems to crash the game

### ISSUE THREAD

**Issue by Kiyaku** [BeetoGuy/BetterWithMods#315]
Crash report: https://pastebin.com/eAVWzdck 

To confirm i made a new pack with just BwM 1.1.6, placed some turn tables and filtered hoppers, saved, updated to 1.1.7 and loaded the world again. That's when i get the crash.
Once in a while it managed to load and turned the turn tables (oh the irony!) into filtered hoppers. But it still crashes sometimes afterwards. 

Let me know if you need any other info!

-SC

**Comment by primetoxinz** [comment]
There may be some hope, but Internal changes in 1.1.7 might have ruined the world. You should be able to load in 1.1.6 again, break all machine blocks, including Filtered Hoppers, Turntables, Cauldron, Crucible and Millstones and try to load in 1.1.7 without them. Once you load the items will not be the same, Cauldron and Crucible were separated into their own block and that changed the item ids for the rest. 

So give this a shot if not maybe worldedit could save it, not sure. My fault for making a breaking change in the middle of a version because we have put it off too long and really needed it.

**Comment by BeetoGuy** [comment]
Yeah, I'll have to agree with that. Better to get it over with before all the other tech mods catch up than have to wait until the 1.12 port to do it. Especially when we don't know how long that will take.

**Comment by Kiyaku** [comment]
Makes sense! It seems like loading that world in 1.1.6 again will work too but it crashes once for every turntable/hopper. After that it's okay. 

Reason i asked is cause i was using it in my modpack and it would probably break worlds of many people (that mod is crucial in making any progress, so it's very likely everyone has BwM blocks placed). 

Do  you have any plans for other big changes or additions for the 1.11 version? I may just keep the modpack version at 1.1.6 for now then. 

I think a little warning on the 1.1.7 file changelog that upgrading from 1.1.6 causes some issues might be useful. 

Thanks for getting back to me so quickly! 
-SC

**Comment by primetoxinz** [comment]
All the major internal changes that need to be made have been for now. If you want to keep compatibility with old worlds staying 1.1.6 is probably the best option, there were a few bug fixes in 1.1.7 that hopefully won't affect many people but not much I can do about that.
Again, my bad for not saying anything about the breaking change, guess I didn't communicate that to @BeetoGuy well enough.

**Comment by BeetoGuy** [comment]
I'll put a warning up on the CurseForge download page.

**Comment by Kiyaku** [comment]
Will keep it on 1.1.6 then, should be fine. Thanks! :D
