### ISSUE TITLE
Hardcore Hunger not compatable with SpiceOfLife

### ISSUE THREAD

**Issue by Hastling** [BeetoGuy/BetterWithMods#32]
When the hardcore hunger is enabled in both client and server configs it causes an "Exception caught during firing event". I've already reported the issue to [SpiceOfLife's github](https://github.com/squeek502/SpiceOfLife/issues/102), ~~but closed the issue once a workaround was found.~~

**Comment by DaedalusGame** [comment]
This seems related to AppleCore patching FoodStats and adding a getPlayer method and their own constructor. When BWM's foodstat replacement fires its constructor it calls super() and the constructor by AppleCore which needs one argument is never triggered and the player field remains null.

**Comment by BeetoGuy** [comment]
So it looks like we'll have to catch AppleCore being loaded and somehow call its constructor. I'll take a look at how to tackle that.

**Comment by squeek502** [comment]
Yeah, this might be a bit tricky. Note that even with the constructor called, there will be other (less crashy) incompatibilities (like BMW's onUpdate being called but not AppleCore's).

Ideally, BMW could optionally use the AppleCore API when it's detected in order to do it's FoodStats stuff instead of overriding the class (see [this wiki article for what's possible with the AppleCore API](https://github.com/squeek502/AppleCore/wiki/Using-the-AppleCore-API)). The only thing I see that AppleCore doesn't currently have support for is changing the max food level, but support for that could be added. Let me know if you'd be interested in trying that.

**Comment by BeetoGuy** [comment]
Yeah, I'd say that's the best option. This seems too big of an incompatibility to ignore.

**Comment by squeek502** [comment]
Sounds good, I'd be happy to write up a proof-of-concept PR for you when I get a chance.

**Comment by BeetoGuy** [comment]
Yeah, I'd appreciate that, thanks. I suppose for now, it would be best for users to disable Hardcore Hunger in the configs.

**Comment by primetoxinz** [comment]
info saved [here](https://github.com/BeetoGuy/BetterWithMods/projects/2)
