### ISSUE TITLE
Is kiln supportive fire working as intended?

### ISSUE THREAD

**Issue by Glease** [BeetoGuy/BetterWithMods#454]
Kiln's speed can be boosted a lot by surrounding more stoked fire to the main fire, however after inspecting source code I found stoked fire on x/z axis is not recognized:

    1. x0x  2. xxx
       0x0     xxx
       x0x     xxx

    Assume x represents a stoked fire

Layout 1 and Layout 2 has same speed. I don't think this is good. [This line](https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/common/blocks/BlockKiln.java#L121) used a boolean or instead of and operator. Is this intentional?

**Comment by DaedalusGame** [comment]
this looks fine to me. it will only iterate over coordinate tuples where atleast one component is != 0. So (1,0) (-1,1) (0,-1) etc. (with boolean and, it would check only diagonals. Because now, both components must not be 0, which is not true for (0,0) and any cardinal direction) Can you check if this actually has an effect ingame?

(that .damageDropped() > 4 is ugly tho)

**Comment by Glease** [comment]
I'm asking if you devs intend to count only fire at diagonal positions is count as valid secondary fire, while ignoring the adjacent ones. This looks werid on the first glance, because theoratically those adjacent ones is even closer to the main fire, and if diagonal ones can support the main fire, why these closer ones can't?

**Comment by DaedalusGame** [comment]
no as in, it should count cardinally adjacent fires as well as diagonally adjacent ones.

**Comment by Glease** [comment]
Sorry, it seems that my jar doesn't match your github source. It must have been either hacked or of wrong version.
