### ISSUE TITLE
[ 1.12 ] Refactoring Mechanical Power for Future Plans

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#484]
To create the discussed plans for Mechanical Power the Block interfaces and any form of power information saved in BlockState likely need to go. This can simplify all of the mechanical power work to a capability attachment through a tileentity.

Most of these tileentities will just be to store the power level will not need to tick at all, most of it can 
just be handled on neighbor update in the block.

A list of blocks that need refactored to use Capabilities: 
 Italic ones do not currently have a tile entity.
- [x] BlockMechMachine
- [x] _BlockSaw_
- [x] _BlockBellows_
- [x] _BlockGearBox_  
      * We might be able to replace this with "Advanced Gearboxes" entirely. 
- [x] BlockCrank
- [x] BlockMillGenerator (Windmill and Waterwheel)
- [x] BlockCreativeGenerator
- [ ] _BlockGearBoostedRail_
- [x] _BlockPump_

Additionally the interface `IOverpowered` should be used to dictate how a block is overpowered.

**Comment by arfink** [comment]
Is this change going to break old worlds?

**Comment by primetoxinz** [comment]
Yes, it will break any mechanical power system.

**Comment by primetoxinz** [comment]
They *may* be recoverable, I am unsure. Best case senario it just removes all the old blocks and you can put them back, worst case it corrupts the whole world :P

**Comment by DaedalusGame** [comment]
forge has a config option for deleting erroring blocks

**Comment by arfink** [comment]
I would like to just chime in here that you can, in fact, load worlds made in 1.3.4 using 2.0.2 without modifying the world save in any way, and without changing settings in Forge. Because the block IDs appear to be changed, Forge will in fact remove them for you, and simply ask for an /fml confirm on the server side in order to boot. The blocks will still have to be replaced, but this is great(ish) news for server admins who would like to upgrade but dread finding every player's creation. It simply nukes them automatically.

**Comment by primetoxinz** [comment]
That's awesome, glad that it worked out!
