### ISSUE TITLE
Wood recipes are not scrubbed entirely

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#531]
Mods like Rustic add extra recipes for oredict compat (ikr???), those recipes remain even if the vanilla wood recipes (like wooden swords, buttons, etc) are removed, circumventing the hardcore gamemodes.

EDIT: this may be a forge issue causing mods to hack around

**Comment by KnightMiner** [comment]
Well, this was a forge issue that is fixed now. Until recently I was not properly replacing vanilla recipes as Mojang switched from wildcard metadata to a static list for thing like wood. As a result some mod authors decided to add their own recipe rather than reporting the issue to Forge or trying to fix it there

**Comment by DaedalusGame** [comment]
yeah, it actually was fixed, i'll report this on Rustic then.
