### ISSUE TITLE
[Bug] Block Dispenser removing NBT data from blocks

### ISSUE THREAD

**Issue by Tetrajak** [BeetoGuy/BetterWithMods#99]
When a block dispenser breaks a block that has NBT data, that NBT data is lost. However, it can place a block with NBT data just fine.

A good modded example of this is an Immersive Engineering storage crate, which tracks its stored items in NBT data, which then loses all the stored items when picked up by a block dispenser.

**Comment by BeetoGuy** [comment]
I had a feeling that would be a potential issue. I'll look into it.

**Comment by BeetoGuy** [comment]
Well, I've got it working, at least for Immersive Engineering.

**Comment by Tetrajak** [comment]
Great to hear! I look forward to getting my hands on the next release!

**Comment by BeetoGuy** [comment]
Just as a note, reviewing what was going on, I remembered that Tinkers tank blocks got harvested with the NBT intact by the Block Dispenser, since the NBT was handled in getDrops() in that case, while IE does it in breakBlock(). Luckily, I was able to get the NBT data from the getPickBlock() method, but it should be noted that if a mod uses breakBlock() to drop items, it won't be as easy to handle NBT cases.
